name: Java CI with Maven
run-name: ${{ github.actor }} is building a java app 🚀
on: [push]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          repository: kunchalavikram1427/actions_demo
      - name: check java and maen versions
        run: | 
          java -version
          mvn --version
