name: GitHub Actions Demo
run-name: GitHub Actions EV demo 🚀
on: [push]
env:
  API_KEY: ${{ secrets.API_KEY }}
jobs:
  Run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo code
        uses: actions/checkout@v4
      - name: get python version
        run: python --version
      - name: read secret
        run: echo ${{ env.API_KEY }}
      - name: Run script
        run: python test.py